config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home_page'
  get 'pages/home_page'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/cancel' => 'devise/registrations#cancel', as: 'cancel_user_registration'
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
    delete 'users' => 'devise/registrations#destroy', as: 'delete_user_registration'
  end

  resources :products, only: [] do
    post :book, on: :member
  end

  resources :companies
  resources :users, only: :index

  resources :outlets, except: :index do
    resources :products, except: :show
    resources :batches, only: %i[create update]
  end
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  has_one :user
  has_many :outlets, dependent: :destroy

  mount_uploader :company_cover, CompanyCoverUploader

  enum company_category: ['Продуктовый магазин', 'Пекарня', 'Кофейня', 'Ресторан']
end

app/controllers/companies_controller.rb
# frozen_string_literal: true

class CompaniesController < ApplicationController
  before_action :set_company, only: %i[show edit update destroy]

  def index
    @companies = Company.all
  end

  def show
    @outlets = @company.outlets
  end

  def new
    @company = Company.new
  end

  def edit; end

  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:company_name, :company_category)
  end
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/views/companies/_form.html.slim
.devise_form
  h2 Управление #{@company.company_name}
  = form_with(model: company, local: true) do |form|
    - if company.errors.any?
      #error_explanation
        h2
          = pluralize(company.errors.count, "error")
          |  prohibited this outlet from being saved:
        ul
          - company.errors.full_messages.each do |message|
            li
              = message
    .company-name-field
      = form.label :Название
      br
      = form.text_field :company_name

    .select-company
      = form.label :Категория
      br
      = form.select :company_category, Company.company_categories.keys

    .button
      = form.submit 'Сохранить', class: 'button_book button'

app/views/companies/_outlet_list.html.slim
.table
  .table-section
    p.table-header Номер
    .content-container
      p = outlet.id

  .table-section
    p.table-header Адрес
    .content-container
      p = display_full_address(outlet.address)

  .table-section
    p.table-header Почта менеджера
    .content-container
      p = outlet.email

  .table-section
    p.table-header Действия
    .content-container
      p = link_to 'Редактировать', edit_outlet_path(outlet, company_id: outlet.company_id)
      p = link_to 'Удалить', outlet, method: :delete, data: { confirm: 'Удалить аутлет?' }

app/views/companies/edit.html.slim
= render 'form', company: @company

= link_to 'Back', company_path(@company)

app/views/companies/index.html.slim
.table-wrapper
  h3 Все компании
  .button_book
   = link_to 'Создать компанию',  new_company_path, class: 'button_book button middle'

  .table
    .table-section
      - @companies.each do |company|
        .content-container
          p = link_to company.company_name, company_path(company)

    .table-section
      - @companies.each do |company|
        .content-container
          p = link_to 'Редактировать', edit_company_path(company)
          p = link_to 'Удалить', company, method: :delete, data: { confirm: 'Вы уверены, что хотите удалить компанию?' }

app/views/companies/new.html.slim
p
= render 'form', company: @company

app/views/companies/show.html.slim
.outlet_container
  .outlet_banner
  .outlet_info
  h1 = @company.company_name
  h4 = @company.company_category
- if can? :manage, Company

.outlet-table_container
  .table-wrapper
    h3 Все аутлеты
    .button_book
     = link_to "Создать новый аутлет", new_outlet_path(company_id: @company.id), class: 'button_book button middle'
    .outlet_list
      - if can? :manage, Outlet
        = render partial: 'outlet_list', collection: @outlets, as: :outlet

      - if can? :manage, :all
        br
          // = link_to "Редактировать компанию", edit_company_path(@company)
          // = link_to 'Назад', companies_path