config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home_page'
  get 'pages/home_page'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/cancel' => 'devise/registrations#cancel', as: 'cancel_user_registration'
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
    delete 'users' => 'devise/registrations#destroy', as: 'delete_user_registration'
  end

  resources :products, only: [] do
    post :book, on: :member
  end

  resources :companies
  resources :users, only: :index

  resources :outlets, except: :index do
    resources :products, except: :show
    resources :batches, only: %i[create update]
  end
end

app/models/batch.rb
# frozen_string_literal: true

class Batch < ApplicationRecord
  has_many :batches_products, dependent: :destroy
  has_many :products, through: :batches_products
  belongs_to :outlet

  accepts_nested_attributes_for :batches_products

  enum discount: %w[25 50 75]

  scope :with_products, lambda {
    joins(:batches_products, outlet: :company)
    .select('batches.*, COUNT(batches_products.id) AS products_count')
    .where('batches_products.quantity > 0')
    .having('COUNT(batches_products.id) > 0')
    .group(:id)
  }
end

app/controllers/batches_controller.rb
# frozen_string_literal: true

class BatchesController < ApplicationController
  before_action :get_outlet

  def create
    @batch = @outlet.batches.build(batch_params)
    @products = @outlet.products

    respond_to do |format|
      if @batch.save
        format.html { redirect_to outlet_products_path(@outlet), notice: 'Updated' }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render 'products/index' }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @batch = @outlet.batches.find(params[:id])
    @products = @outlet.products

    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to outlet_products_path(@outlet), notice: 'Batch was successfully updated.' }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render 'products/index' }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def batch_params
    params.require(:batch).permit(
      :discount,
      :activation_start,
      :activation_end,
      batches_products_attributes: %i[product_id quantity id]
    )
  end

  def get_outlet
    @outlet = Outlet.find(params[:outlet_id])
  end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_form.html.erb
<%= form_with(model: batch, local: true) do |form| %>
  <% if batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
      <% batch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.input :tag_list %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/batches/edit.html.erb
<h1>Editing Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Show', @batch %> |
<%= link_to 'Back', batches_path %>

app/views/batches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Batches</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= batch.company_name %></td>
        <td><%= link_to 'Show', batch %></td>
        <td><%= link_to 'Edit', edit_batch_path(batch) %></td>
        <td><%= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Batch', new_batch_path %>

app/views/batches/new.html.erb
<h1>New Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Back', batches_path %>

app/views/batches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @batch.company_name %>
</p>

<%= link_to 'Edit', edit_batch_path(@batch) %> |
<%= link_to 'Back', batches_path %>

<%= render 'products/index' %>