config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home_page'
  get 'pages/home_page'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/cancel' => 'devise/registrations#cancel', as: 'cancel_user_registration'
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
    delete 'users' => 'devise/registrations#destroy', as: 'delete_user_registration'
  end

  resources :products, only: [] do
    post :book, on: :member
  end

  resources :companies
  resources :users, only: :index

  resources :outlets, except: :index do
    resources :products, except: :show
    resources :batches, only: %i[create update]
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :batches_products, dependent: :destroy
  has_many :batches, through: :batches_products
  belongs_to :outlet

  mount_uploader :product_pic, ProductPicUploader

  # data enumerizers
  enum weight_type: ['на вес', 'в порциях']

  enum category: ['Кулинария', 'Бакалея', 'Вегетарианское', 'Напитки', 'Сладкое']
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :get_outlet, except: :book
  before_action :set_product, only: %i[edit update destroy]

  def index
    @batch = @outlet.batches.where('DATE(activation_start) = ?' , Date.current.to_s).first
    @batch ||= @outlet.batches.build
    @products = @outlet.products
  end

  def new
    @product = @outlet.products.build
  end

  def edit; end

  def create
    @product = @outlet.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to outlet_products_path(@outlet), notice: 'Продукт добавлен.' }
        # format.json { render :index, status: :created, location: @product }
      else
        format.html { render :new, notice: 'Ошибка' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to outlet_products_path(@outlet), notice: 'Product was successfully updated.' }
        # format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to outlet_products_path(@outlet), notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def book
    @product = Product.find(params[:id])
    ProductMailer.with(
      product: @product, email: params[:email], code: params[:code]
    ).book_code.deliver_later

    head :no_content
  end

  private

  def set_product
    @product = @outlet.products.find(params[:id])
  end

  def get_outlet
    @outlet = Outlet.find(params[:outlet_id])
  end

  def product_params
    params.require(:product).permit(
      :name,
      :price,
      :weight_type,
      :weight_amount,
      :product_pic,
      :category
    )
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_batch_product_card.html.slim
.batch_product_card
  .cover
    = image_tag product.product_pic.to_s

  .batch_product_card_info
    .details
      h4 #{product.name}
      h3.disabled_price #{product.price} &#8381;

      - if product.price && batch.discount
        - discount_sum = product.price * batch.discount.to_i / 100
        h3 #{product.price - discount_sum} &#8381;

      .quantity
        p.dark_grey Цена за #{product.weight_amount} #{product.weight_type}
        .button_quantity.button
          span.decrease_quantity -
          - current_batch_product = batch.batches_products.find_by(product_id: product.id)
          span.quantity_value data-product_id=product.id data-batch_product_id=(current_batch_product&.id || '')
            = current_batch_product&.quantity || 0
          span.increase_quantity +
      .buttons
        = link_to 'Редактировать', edit_outlet_product_path(product.outlet, product),
          class: 'button_edit button'
        = link_to 'Удалить', outlet_product_path(product.outlet, product),
          method: :delete, data: { confirm: 'Вы уверены, что хотите удалить продукт?' },
            class: 'button_delete button'

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label "Категория продукта" %>
    <%= form.select :category, Product.categories.keys %>
  </div>

  <div class="field">
    <%= form.label "Тип продукта" %>
    <%= form.select :weight_type, Product.weight_types.keys %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :sale_price %>
    <%= form.number_field :sale_price %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="field">
    <%= form.label :batch_id %>
    <%= select("product", "batch_id", Batch.all.collect {|b| [b.company_name, b.id]}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_form.html.slim
= form_with(model: product, url: [outlet, product], local: true, html: {class: "product_form"}) do |form|
  .new_product
    = form.file_field :product_pic, class: 'file_field'
    .bread_form

  h2 #{form.text_field :name, placeholder: 'Введите название товара', size: 30, class: 'title_input'}

  hr.separator

  .measure
    = form.select :category, Product.categories.keys,
      class: 'button_category button', placeholder: 'Выберитe категорию'

    .radio_button
    = form.radio_button :weight_type, 'в порциях'
    = form.label :weight_type, "в порциях", value: 'в порциях'

    .radio_button
    - checked = product.weight_type.nil?
    = form.radio_button :weight_type, 'на вес', checked: checked
    = form.label :weight_type, "на вес", value: 'на вес'

  .measure_inputs
    .measure_input
      p #{form.label :weight_amount, 'Вес порций'}
      = form.text_field :weight_amount, placeholder: 0, class: 'input'

    .measure_input
      p #{ form.label :price, 'Цена без скидки' }
      = form.text_field :price, placeholder: 0, class: 'input'

  .buttons
    = link_to 'Отмена', outlet_products_path(outlet), class: 'button_edit button middle'
    = form.submit 'Сохранить', class: 'button_book button middle'

app/views/products/_index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Weight type</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Sale price</th>
      <th>Company name</th>
      <th>Batch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td class="product-pic"><%= image_tag product.product_pic.url %></td>
        <td><%= link_to product.name, product %></td>
        <td><%= product.category %></td>
        <td><%= number_to_human(product.weight_quantity, units: {unit: "г", thousand: "кг"}) %></td>
        <td><%#= product.weight_quantity %></td>
        <td><%= product.weight_type %></td>
        <td><%= product.quantity %></td>
        <td><%= product.price %></td>
        <td><%= product.sale_price %></td>
        <td><%= product.company_name %></td>
        <td><%= product.batch_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/edit.html.slim
.title
  .background
  h1  Редактировать #{@product.name}
  hr.separator

= render 'form', product: @product, outlet: @outlet

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Weight type</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Sale price</th>
      <th>Company name</th>
      <th>Batch</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td class="product-pic"><%= image_tag product.product_pic.url %></td>
        <td><%= link_to product.name, product %></td>
        <td><%= product.category %></td>
        <td><%= number_to_human(product.weight_quantity, units: {unit: "г", thousand: "кг"}) %></td>
        <td><%#= product.weight_quantity %></td>
        <td><%= product.weight_type %></td>
        <td><%= number_to_currency(product.price, unit: "₽", separator: ",", delimiter: "", format: "%n %u") %></td>
        <td><%= link_to product.user.company_name, users_profile_url %></td>

        <% if can? :update, Product %>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <% end %>

        <% if can? :destroy, Product %>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/index.html.slim
.title
  .background
  h1  Новая акция
  hr.separator

.products_container
  = link_to new_outlet_product_path do
    .new_product
      .add
      h3 Добавить продукт

  - @products.each do |product|
    = render partial: 'batch_product_card', locals: {product: product, batch: @batch}

= form_with(model: @batch, url: [@outlet, @batch], local: true, html: {class: 'batch_form' }) do |form|

  .batch-panel
   .discount_start
      div
        = form.label "Начало акции"
        = form.time_field :activation_start, step: 60

   .discount_end
      div
        = form.label "Конец акции"
        = form.time_field :activation_end

   .discount_amount
      = form.label "Скидка на партию"
      = form.select :discount, Batch.discounts.keys

   .button
    .actions-batch
     = form.submit "Сохранить изменения", class: 'button_save button'

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/new.html.slim
.title
  .background
  h1  Новый продукт
  hr.separator

= render 'form', product: @product, outlet: @outlet

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= Category.find(@product.category_id).title %>
</p>

<p>
  <strong>Weight type:</strong>
  <%= @product.weight_type %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Sale price:</strong>
  <%= @product.sale_price %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @product.company_name %>
</p>

<p>
  <strong>Batch:</strong>
  <%= @product.batch_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>