config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home_page'
  get 'pages/home_page'

  devise_for :users, skip: [:registrations]
  as :user do
    get 'users/cancel' => 'devise/registrations#cancel', as: 'cancel_user_registration'
    get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    put 'users' => 'devise/registrations#update', as: 'user_registration'
    delete 'users' => 'devise/registrations#destroy', as: 'delete_user_registration'
  end

  resources :products, only: [] do
    post :book, on: :member
  end

  resources :companies
  resources :users, only: :index

  resources :outlets, except: :index do
    resources :products, except: :show
    resources :batches, only: %i[create update]
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    alias_action :create, :read, :update, :destroy, :to => :crud

    user ||= User.new # guest user (not logged in)

    if user.role == 'admin'
      can :manage, :all

    elsif user.role == 'retailer'
      can :manage, Company, :id => user.company_id
      can :manage, Outlet, :company_id => user.company_id

    elsif user.role == 'manager'
      can :manage, [Batch, Product], :outlet_id => user.outlet_id
      can [:read, :update], Outlet, :id => user.oulet_id

    else
      can :read, [Outlet, Batch, Product]
      cannot :index, User
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batch.rb
# frozen_string_literal: true

class Batch < ApplicationRecord
  has_many :batches_products, dependent: :destroy
  has_many :products, through: :batches_products
  belongs_to :outlet

  accepts_nested_attributes_for :batches_products

  enum discount: %w[25 50 75]

  scope :with_products, lambda {
    joins(:batches_products, outlet: :company)
    .select('batches.*, COUNT(batches_products.id) AS products_count')
    .where('batches_products.quantity > 0')
    .having('COUNT(batches_products.id) > 0')
    .group(:id)
  }
end

app/models/batches_product.rb
# frozen_string_literal: true

class BatchesProduct < ApplicationRecord
  belongs_to :batch
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
  has_one :user
  has_many :outlets, dependent: :destroy

  mount_uploader :company_cover, CompanyCoverUploader

  enum company_category: ['Продуктовый магазин', 'Пекарня', 'Кофейня', 'Ресторан']
end

app/models/outlet.rb
# frozen_string_literal: true

class Outlet < ApplicationRecord
  has_one :user
  belongs_to :company
  has_many :products, dependent: :destroy
  has_many :batches, dependent: :destroy
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :batches_products, dependent: :destroy
  has_many :batches, through: :batches_products
  belongs_to :outlet

  mount_uploader :product_pic, ProductPicUploader

  # data enumerizers
  enum weight_type: ['на вес', 'в порциях']

  enum category: ['Кулинария', 'Бакалея', 'Вегетарианское', 'Напитки', 'Сладкое']
end

app/models/user.rb
# frozen_string_literal: true
class User < ActiveRecord::Base
  belongs_to :company, optional: true
  belongs_to :outlet, optional: true

  devise :invitable, :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/batches_controller.rb
# frozen_string_literal: true

class BatchesController < ApplicationController
  before_action :get_outlet

  def create
    @batch = @outlet.batches.build(batch_params)
    @products = @outlet.products

    respond_to do |format|
      if @batch.save
        format.html { redirect_to outlet_products_path(@outlet), notice: 'Updated' }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render 'products/index' }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @batch = @outlet.batches.find(params[:id])
    @products = @outlet.products

    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to outlet_products_path(@outlet), notice: 'Batch was successfully updated.' }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render 'products/index' }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def batch_params
    params.require(:batch).permit(
      :discount,
      :activation_start,
      :activation_end,
      batches_products_attributes: %i[product_id quantity id]
    )
  end

  def get_outlet
    @outlet = Outlet.find(params[:outlet_id])
  end
end

app/controllers/outlets_controller.rb
class OutletsController < ApplicationController

  before_action :set_outlet, only: %i[show edit update destroy]
  before_action :set_company, only: %i[new create]

  def show
    @batch = @outlet.batches.where(
      'DATE(activation_start) = ? AND activation_end > ?' , Date.current.to_s, Time.current
    ).first
    @products = @batch&.products
  end

  def new
    @outlet = @company.outlets.new
  end

  def edit
  end

  def create
    @outlet = @company.outlets.build(outlet_params)

    respond_to do |format|
      if @outlet.save
        format.html { redirect_to company_path(@company), notice: 'Outlet was successfully created.' }
        format.json { render :show, status: :created, location: @outlet }
      else
        format.html { render :new }
        format.json { render json: @outlet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @outlet.update(outlet_params)
        format.html { redirect_to company_path(@outlet.company), notice: 'Outler was successfully updated.' }
        format.json { render :show, status: :ok, location: @outlet }
      else
        format.html { render :edit }
        format.json { render json: @outlet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @outlet.destroy
    respond_to do |format|
      format.html { redirect_to company_path(@outlet.company), notice: 'Outlet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_outlet
    @outlet = Outlet.find(params[:id])
  end

  def set_company
    @company = Company.find(params[:company_id])
  end

  def outlet_params
    params.require(:outlet).permit(:email, address: %i[city street apartment block])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home_page
    @current_batches =
      Batch
      .with_products
      .where('activation_start < ? AND activation_end > ?', Time.current, Time.current)
      .limit(3)
    @future_batches =
      Batch
      .with_products
      .where(
        'DATE(activation_start) = ? AND activation_start > ?' , Date.current.to_s, Time.current
      )
      .limit(9)
    @all_batches =
      Batch
      .with_products
      .where(
        'DATE(activation_start) = ? AND activation_end > ?' , Date.current.to_s, Time.current
      )
  end
end

app/controllers/users_controller.rb
  # frozen_string_literal: true

class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/companies_helper.rb
# frozen_string_literal: true

module CompaniesHelper
end

app/helpers/outlets_helper.rb
module OutletsHelper
  def display_full_address(address)
    return '' if address.blank?


    "#{address['city']}, #{address['street']}, д. #{address['apartment']}, #{address['block']}"
  end

  def display_title_address(address)
    return '' if address.blank?

    "#{address['street']}"
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def navbar_path(user)
    case user.role
    when 'admin'
      root_path
    when 'retailer'
      company_path(user.company)
    when 'manager'
      outlet_products_path(outlet_id: user.outlet_id)
    else
      root_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Каталог товаров', categories_path %>
    <%= link_to 'Список заведений' %>
    <%= link_to 'Специальные предложения'%>
    <nav>
      <div>
        <%= link_to 'Фид', feed_index_url %>
        <%= link_to 'Продукты', products_path %>
        <%= link_to 'Партии', batches_path if can? :index, Batch %>
      </div>


      <div>

        <% if user_signed_in? %>
          <%= link_to current_user.company_name, users_profile_url %>
          <%= link_to('Выйти', destroy_user_session_path, method: :delete) %>
        <% else %>
          <%= link_to('Войти', new_user_session_path) %>
          <%= link_to('Регистрация', new_user_registration_path) %>
        <% end %>
      </div>
    </nav>

  <%= yield %>

  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | DAR
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'

    link href="//db.onlinewebfonts.com/c/264e8767769e1b5b33e24efbecade995?family=CoFo+Sans" rel="stylesheet" type="text/css" /
  body
    nav.navbar
      .info
        = link_to root_path do
          .logo
        /.location Some location

      - if user_signed_in?
        .user_login
          #= link_to current_user.email, navbar_path(current_user)
          - if current_user.role == 'admin'
              = link_to "Компании", companies_path
              = link_to "Пользователи", users_path
              = link_to "Отправить приглашение", new_user_invitation_path
          .logout
            = link_to 'Выход', destroy_user_session_path, method: :delete

      - else
        .login
          = link_to 'Войти', new_user_session_path

    .container
      = yield

      hr.footer_separator.separator
      footer
        p © 2019-2020 «DAR»

        .footer
          p Как забрать товар?
          p Компаниям
          p Благотворителям(beta)

app/views/layouts/devise.html.slim
doctype html
html
  head
    title
      | DAR
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'


    link href="//db.onlinewebfonts.com/c/264e8767769e1b5b33e24efbecade995?family=CoFo+Sans" rel="stylesheet" type="text/css" /
  body
    nav.navbar
      .info
        = link_to root_path do
          .logo
        /.location Some location

    .devise_container
      = yield

app/views/pages/home_page.html.slim
.react-instructions-banner

.menubar
  hr.separator
  .items
    h4.menu_item Все
    - Company.company_categories.each do |key, i|
      h4.menu_item onclick="checkClick(this, '#{i}')" #{key}
  hr.separator

.batch
  - if @current_batches.any?
    .batch_block
      .batch_block_title
        h2 Активные акции
      //  a.orange Показать все

      .batch_block_cards
        - @current_batches.limit(6).each do |batch|
          = render partial: 'outlets/outlet_card', locals: { outlet: batch.outlet, batch: batch }

    hr.separator

  - if @future_batches.any?
    .batch_block
      .batch_block_title
        h2 Будущие акции
      //  a.orange Показать все
      .batch_block_cards
        - @future_batches.limit(6).each do |batch|
          = render partial: 'outlets/outlet_card',locals: { outlet: batch.outlet, batch: batch }

    hr.separator

  - if @all_batches.any?
    .companies
      .batch_block_title
        h2 Все заведения в вашем районе

      .batch_block_cards
        - @all_batches.each do |batch|
          = render partial: 'outlets/outlet_card',locals: { outlet: batch.outlet, batch: batch }

    - Company.company_categories.each do |category_name, index|
      - category_batches = @all_batches.where(companies: { company_category: index })
      - next if category_batches.blank?

      hr.separator
      .batch_block
        .batch_block_title
          h2[id = "category_#{index}"] = category_name

        .batch_block_cards
         - category_batches.each do |batch|
           = render partial: 'outlets/outlet_card',locals: { outlet: batch.outlet, batch: batch }